"""Update models to match database schema

Revision ID: 27deb146b100
Revises: 1f442ba6bb81
Create Date: 2025-03-17 22:38:17.155388

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '27deb146b100'
down_revision: Union[str, None] = '1f442ba6bb81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('operating_hours', 'opening_time',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Time(),
               existing_nullable=True,
               postgresql_using="opening_time::time without time zone")
    op.alter_column('operating_hours', 'closing_time',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Time(),
               existing_nullable=True,
               postgresql_using="closing_time::time without time zone")
    op.drop_constraint('operating_hours_outlet_id_fkey', 'operating_hours', type_='foreignkey')
    op.create_foreign_key(None, 'operating_hours', 'outlets', ['outlet_id'], ['id'], ondelete='CASCADE')
    op.drop_column('operating_hours', 'created_at')
    op.drop_column('operating_hours', 'updated_at')
    op.alter_column('outlets', 'name',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('outlets', 'waze_link',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('outlets', 'latitude',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=8),
               existing_nullable=True)
    op.alter_column('outlets', 'longitude',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=11, scale=8),
               existing_nullable=True)
    op.alter_column('outlets', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('outlets', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('outlets', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('outlets', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('outlets', 'longitude',
               existing_type=sa.Numeric(precision=11, scale=8),
               type_=postgresql.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('outlets', 'latitude',
               existing_type=sa.Numeric(precision=10, scale=8),
               type_=postgresql.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('outlets', 'waze_link',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
    op.alter_column('outlets', 'name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.add_column('operating_hours', sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
    op.add_column('operating_hours', sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'operating_hours', type_='foreignkey')
    op.create_foreign_key('operating_hours_outlet_id_fkey', 'operating_hours', 'outlets', ['outlet_id'], ['id'])
    op.alter_column('operating_hours', 'closing_time',
               existing_type=sa.Time(),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)
    op.alter_column('operating_hours', 'opening_time',
               existing_type=sa.Time(),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)
    # ### end Alembic commands ###
